### ISSUE TITLE
Site registry model

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#531]
## Data model

* [x] id: (pk, string) slugified name of site. Could be an FK to site registry, but not critical.
* [x] settings (jsonb) all the meta data for a given site (info for instance administrators, not for site administrators)

## Tasks

* [x] create model
* [x] write method that reads the config for a site from the CSV/Spreadsheet used by site admin, and writes that current config into the DB (destructive, overwrite the settings property)
* [x] Make /admin/registry/ job that is only available to instance admins
* [x] Write test for the CSV > DB function
