### ISSUE TITLE
Site config model

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#532]
## Data model

* [x] id: (pk, string) slugified name of site. Could be an FK to site registry, but not critical.
* [x] settings (jsonb) all the settings for a given site

## Tasks

* [x] create model
* [x] refactor all uses of config to take data from the database
* [x] write method that reads the config for a site from the CSV/Spreadsheet used by site admin, and writes that current config into the DB (destructive, overwrite the settings property)
* [x] Make /admin/reload/ work with above method
* [x] Write test for the CSV > DB function
