### ISSUE TITLE
Subdomain routing for sites

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#533]
## Tasks

* [x] Add the express-subdomains lib: https://www.npmjs.com/package/express-subdomain
* [x] Change the basic routing of the app so that it supports subdomains
* [x] Setup hosts file (/etc/hosts) or whatever with two example domains: demo.census.dev and us-city.census.dev - we'll use these for development
* [x] When a request comes in for a subdomain, maps the subdomain to an ID in the meta table
* [x] If there is no match in the meta table, show a not found page
* [x] Document the interaction of Registry, Site, and the subdomain routing
