### ISSUE TITLE
Admin actions

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#534]
## Background

The current version of the code has a single action that can be made by site administrations: "Reload the config". This is implemented as a route, accessible by administrators ([route](https://github.com/okfn/opendatacensus/blob/feature/database/routes/index.js#L588) / [url](https://github.com/okfn/opendatacensus/blob/feature/database/app.js#L144)).

Using a URL is useful, and we want to retain this pattern for all actions that we allow administrators to do. The new code has several more actions, so we need to implement these in this pattern.

In addition, we also want to create a simple page that exposes these same actions as "buttons the admin can click".

## Tasks

* [x] The existing `/admin/reload` should be changed to `/admin/reload/config`
* [x] Ensure that `/admin/reload/config` works with the new loaders https://github.com/okfn/opendatacensus/issues/547, and only loads the config of the currently active site
* [x] Add a new `/admin/reload/places` action, accessible only to admins, that reloads the currently active site's places
* [x] Add a new `/admin/reload/datasets` action, accessible only to admins, that reloads the currently active site's datasets
* [x] Add a new `/admin/reload/questions` action, accessible only to admins, that reloads the currently active site's questions
* [x] Add a new `/admin/reload/registry` action, that reloads the registry
* [x] Add a simple page at `admin/reload`, which has a button for each of the above admin actions
  * [x] The button can just make a GET request to each action at this stage.

**Comment by pwalsh** [comment]
Done in https://github.com/okfn/opendatacensus/tree/feature/database
