### ISSUE TITLE
Entry model

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#539]
## Tasks

* [x] create model
* [x] write method that reads the config for a site from the CSV/Spreadsheet used by site admin, and writes that current config into the DB (destructive, overwrite the settings property)
* [x] Make /admin/datasets/ job that is only available to instance admins
* [x] Write test for the CSV > DB function
