### ISSUE TITLE
Write data loaders from Spreadsheet to Database

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#547]
## Background

Data is currently in spreadsheets. We need to migrate it into the database. This involves a few steps:

1. Read the data from the spreadsheet(s)
2. Parse the data into objects & properties that we need for our new [data model](https://github.com/okfn/opendatacensus/tree/feature/database/models)
3. Write these new objects to the database

We have a couple of different, yet related, scenarios for loading data:

1. One off/bulk data load - eg: for the database (Entry), and the users (User)
2. Repeatable, "instance-wide" data load - eg: for the Registry, which is managed by the system admin
3. Repeatable, "site-specific" data load - eg: for Site, Place, Dataset and Question models/sheets

While each of these have different use cases, the loading principle is the same. Further more, we already have code in the codebase that takes care of step 1 - reading data from the spreadsheets.

* Current code for reading data from spreadsheets:
  * https://github.com/okfn/opendatacensus/blob/feature/database/lib/util.js#L73
  * https://github.com/okfn/opendatacensus/blob/feature/database/lib/util.js#L126
  * https://github.com/okfn/opendatacensus/blob/feature/database/lib/util.js#L216

## Tasks

* [x] Write functions for each data type we need to load, in the [`loaders` module](https://github.com/okfn/opendatacensus/blob/feature/database/loaders/index.js)
  * Use the existing code for reading data as much as possible, but bring it into the `loaders` module and refactor as needed
* [x] Parse the data that is read into the required objects for the database models, and save to the database
  * [x] `loaders.getRegistry` > `models.Registry` 
  * [x] `loaders.getConfig` > `models.Site` 
  * [x] `loaders.getPlaces` > `models.Place` 
  * [x] `loaders.getDatasets` > `models.Dataset` 
  * [x] `loaders.getQuestions` > `models.Question`
* [x] ensure that all field names are always lowercased (users often have a mixture of cases - we want to force to lower when we use this data in code)
* [x] Handle translation fields: Places, Datasets and Questions can have translation fields - see "Questions" in our demo sheets - there are example translation fields there
  * translation fields are of format "{field_name}@{lang}" - so "@" is a special character
  * each of these models has a `translation` property which is a jsonb field
  * [x] translations are to go in this object, keyed by language. example of how it should look is below 
* [x] Write unit tests in this file for [loader tests[(https://github.com/okfn/opendatacensus/blob/feature/database/tests/loaders.js). For each loader, write:
  * [x] test can read data from spreadsheet
  * [x] test can read same data out of database after saving

example translations object:

```
{
  "de": {
    "question": "the question text in german",
    "description": "the description text in german"
  },
  "es": {
    "question": "the question text in spanish",
    "description": "the description text in spanish"
  }
}
```
