### ISSUE TITLE
Rewrite the queries in the routes

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#548]
## Background

Data is currently in spreadsheets, and there is a custom "ORM" type query layer written on top of that, to create objects, dereference relations, and so on. After completing the loaders task https://github.com/okfn/opendatacensus/issues/547, we will have data in our database, and we will use the Sequelize ORM for the query layer. 

An additional concern that we do not have in the existing codebase is that all queries need to be site specific - filtered by site. Whether we stay with the first model implementation of composite primary keys on id + site for most data, or we change it to some type of "unique together" implementation on those models, we must ensure that each query for the route layer is site specific.

* Current code for queries and routes:
  * [All routes have been consolidated here for now](https://github.com/okfn/opendatacensus/blob/feature/database/routes/index.js)
  * [The custom query layer over google spreadsheets is here](https://github.com/okfn/opendatacensus/blob/feature/database/lib/model.js)

## Tasks

* [x] Refactor all the routes to use the ORM

**Comment by Basya-Zp** [comment]
@pwalsh 
Could you please clarify this task? Do you want me to create model-based methods to process some actions. Lie

**Comment by Basya-Zp** [comment]
@pwalsh 
Could you please clarify this task? Do you want me to create model-based methods to process some actions. 
Like I can create 'findOne(query)', 'update(query)' methods in 'Site', 'Questions' etc. models or what?

**Comment by gvidon** [comment]
General part of migrating to Sequelize is done. Only TODOs are left:
 
- [ ] translation
- [ ] ```ynquestions```

**/overview**
- [ ] datasets count https://github.com/okfn/opendatacensus/blob/feature/database/census/controllers/pages.js#L12
- [ ] summary — open entries  @pwalsh which Entry is considered to be *open*?
- [ ] summary — open entries percent
- [ ] list of entries by place https://github.com/okfn/opendatacensus/blob/feature/database/census/controllers/pages.js#L38

**/dataset**
- [ ] list of dataset entries
- [ ] places
- [ ] questions

**/submit**
- [ ] proper flashing of messages https://github.com/okfn/opendatacensus/blob/feature/database/census/controllers/census.js#L51

**Comment by pwalsh** [comment]
@gvidon that's great! BTW, I already created the mixin for translations: https://github.com/okfn/opendatacensus/blob/feature/database/census/models/mixins.js

all our translated models have it available as an instance method. Didn't check it though, as when I added it there was no working thing to check :).

**Comment by gvidon** [comment]
@pwalsh I'm a bit confused with a entity name used in label and in template variable — https://www.dropbox.com/s/t3jy89zsu42uho6/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-02%2012.32.04.png?dl=0

Is this summary for ```Dataset``` or ```Entry```?

**Comment by gvidon** [comment]
Went with ```Entry``` in the last commit.

**Comment by gvidon** [comment]
@pwalsh what is ```.ycount``` https://github.com/okfn/opendatacensus/blob/develop/lib/util.js#L352? Where can I find it in current implementation?

**Comment by pwalsh** [comment]
@gvidon these are the tricky bits. I'll have to dive in a bit later today. Just go ahead on what you can, and we'll sync on it a bit later.

**Comment by gvidon** [comment]
@pwalsh ok, no problem
