### ISSUE TITLE
Site routing

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#549]
## Background

The current version of the code serves one "site". The new version of the code will serve many sites - one on each subdomain. Sites are listed in the [Registry model](https://github.com/okfn/opendatacensus/blob/feature/database/models/registry.js), and have their configuration details in the [Site model](https://github.com/okfn/opendatacensus/blob/feature/database/models/site.js).

In order to support this, we've added the [`subdomain` middleware to our app](https://github.com/okfn/opendatacensus/blob/feature/database/app.js#L88) ([here is the library itself](https://github.com/edwardhotchkiss/subdomain)). This gives us `req.params.domains` that we can use in our routes.

However, before we let any request get to our route layer, we need to ensure that the new site (the subdomain) is in our Registry, and has a Site object. If not, we need to show a 404.

## Tasks

* [x] Write a new middleware that:
  * [x] checks if the subdomain matches an entry in Registry
    * [x] If no match in Registry, return a 404, with the message "You requested an unknown census"
  * [x] then, checks that the subdomain macthes an entry in Site
    * [x] If no match in Site, return a 404, with the message "This Site is awaiting configuration. Check back soon"
  * [x] If we have the match in Registry and Site, then allow the request to proceed

**Comment by pwalsh** [comment]
done in https://github.com/okfn/opendatacensus/tree/feature/database
