### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#550]
## Background

The current version of the code has users, and also allows anonymous login. We are going to change how users work - but still base everything on passport.js

## Tasks

* [x] Remove any existing code for anonymous login
* [x] Setup our user model with all [fields we need for passport](http://passportjs.org/docs/profile)
  * [x] Add a property called "anonymous" to the user model
* [x] Implement these passport.js strategies:
  * [x] [Local](https://github.com/jaredhanson/passport-local)
  * [x] [Google](https://github.com/jaredhanson/passport-google-oauth) - this already exists in code, but please check for consistency with other strategies we implement
  * [x] [Facebook](http://passportjs.org/docs/facebook)
* [x] Update the login page to reflect the new methods
  * user can set "anonymous" if she uses local strategy. for others, we'll later have to expose a profile page so user can change to anonymous
* [x] ensure that all places that interact with users in the code use the new implementation 

**NOTE**: some of this work has been started.

* Here are routes: https://github.com/okfn/opendatacensus/blob/feature/database/routes/auth.js#L8
* Here are the strategies (maybe move them?): https://github.com/okfn/opendatacensus/blob/feature/database/routes/utils.js

**Comment by morchickit** [comment]
@pwalsh Can change the Facebook to Twitter (or add Twitter)? I know a lot of people in the space use it.

**Comment by pwalsh** [comment]
Twitter auth does not give us the user's email, which we need for the plans around review/submit discussion.

**Comment by Basya-Zp** [comment]
@pwalsh 
So, as I understand you want me to do the following:
- update User Model to get it suitable with 'Passport'
- update User Model with 'anonymous' field
- check current Google Strategy 
- create new strategy for Local login
- create Facebook-based strategy

Could you please confirm?

**Comment by pwalsh** [comment]
@Basya-Zp that's right.

**Comment by gvidon** [comment]
@pwalsh is anything from this todo list done?

**Comment by pwalsh** [comment]
@gvidon 

Some strategies where added here: https://github.com/okfn/opendatacensus/blob/feature/database/census/routes/utils.js#L4

Old app already had google login (https://github.com/okfn/opendatacensus/blob/feature/database/census/routes/auth.js#L8 and https://github.com/okfn/opendatacensus/blob/feature/database/census/routes/auth.js#L33)

And the model was updated: https://github.com/okfn/opendatacensus/blob/feature/database/census/models/user.js

**Comment by gvidon** [comment]
@pwalsh should I remove this UI?

https://www.dropbox.com/s/j5x5nu9e1jkcpjp/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-06-22%2012.16.17.png?dl=0

**Comment by pwalsh** [comment]
yes.

**Comment by gvidon** [comment]
@pwalsh all done, except password encryption — https://github.com/okfn/opendatacensus/blob/feature/database/census/routes/utils.js#L108 Not sure on how to do this.

**Comment by pwalsh** [comment]
In Sequelize, I'm not sure either. But I see this: http://docs.sequelizejs.com/en/latest/api/datatypes/#virtual

WDYT?

**Comment by gvidon** [comment]
@pwalsh ok, will try it

**Comment by gvidon** [comment]
* Done encryption with salt
* all auth strategies now return ```User``` model.
