### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#552]
Updates to the test suite for new code.

# Tasks

* [x] Build a basic set of fixtures. 
  * I began this work [here](https://github.com/okfn/opendatacensus/tree/develop/fixtures), it just needs fleshing out with "entry" objects
* [x] Remove tests that are no longer relevant
  * I did most of this. The focus should now be on `tests/app.js` and `tests/loaders.js`
* [x] Get all tests in `tests/app.js` passing using fixtures and Zombie.js
* [x] Get all tests in `tests/loaders.js` passing using fixtures and Zombie.js

After this, we can close this initial issue, and open a new one with any specific tests we want to add due to deeper changes in code.

**Comment by gvidon** [comment]
e72ae43195e1e19c62d51b8550ac1e96798cf3ab
e72ae43195e1e19c62d51b8550ac1e96798cf3ab

**Comment by gvidon** [comment]
Stuck with a very weird exception https://www.dropbox.com/s/jw0o4g9h47rri9d/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-13%2017.54.46.png?dl=0

It tends to go away when I comment out several test cases ```it()``` above.

**Comment by pwalsh** [comment]
Looks like a known issue with mocha and promises. I'll be able to look tomorrow too, but meanwhile see:

http://thanpol.as/nodejs/Mocha-and-Promises-No-Problem/

https://lostechies.com/derickbailey/2012/08/17/asynchronous-unit-tests-with-mocha-promises-and-winjs/

for reference and solutions.

**Comment by gvidon** [comment]
All uncommented tests passed.

**Comment by pwalsh** [comment]
right on :). Thanks @gvidon

**Comment by pwalsh** [comment]
@gvidon I **cannot** get the test changes you did running. If you have time can you take a look? I commented them for now so that we can see the other tests passing.

**Comment by pwalsh** [comment]
@gvidon please take a look.

**Comment by pwalsh** [comment]
@kravets-levko can you take this from here, and use Zombie.js to adapt tests in app.js and loaders.js

**Comment by borysyuk** [comment]
https://github.com/okfn/opendatacensus/pull/718
Get all tests in tests/loaders.js passing using fixtures and Zombie.js - Done
