### ISSUE TITLE
Allow comments on a submission

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#581]
# User story

As a “Reviewer” or Visitor I want to leave a comment on a submission so that an improvement or omission can be highlighted and addressed.

# Implementation

First, note that the system already has a config setting for a "disqus forum" [here](https://github.com/okfn/opendatacensus/blob/develop/census/config/index.js#L32).

On a submission page. Underneath the display of data/the review form, we will have a disqus thread for any visitor to make a comment on the submission.

In order to encourage comments, we also need a small "widget" that floats next to the submission data. This widget should present a call to action for the visitor with the words "Comment on this submission". Clicking on the widget will scroll the user down to the disqus thread, where she can comment using the normal disqus mechanisms.

# UI Mock

<img src="https://docs.google.com/drawings/d/1fpGm7uTEXN4wH448cFLMiOcPJMBjUACtCnJcHsHnzbQ/pub?w=1214&amp;h=714">

# Tasks

* [x] Reinstate the HTML for displaying the disqus thread on any submission page. [Here is the html that we had]
(https://github.com/okfn/opendatacensus/blob/0f2440ea190d9eac1d0eb985b2537bbfad494165/templates/submission/review.html#L70). (Submission pages use the [review.html template](https://github.com/okfn/opendatacensus/blob/develop/census/views/review.html))
* [x] Ensure that the commenting works (just in case there is some additional disqus config that we don't have/have missed)
* [x] Add the HTML widget for that will move along on the right-hand side, next to the submission data.
  * [x] Widget scrolls with user, stopping at the top of the submission data, and the bottom of the submission data (there does nto seem to be a wrapping div for the questions + the text detail, so you may add one in order to define the bounds of the comment call to action)
  * [x] Clicking on the widget takes the user down to the disqus thread

**Comment by pwalsh** [comment]
@morchickit see the mocks, note the planned implementation, and add any comments here :).

**Comment by morchickit** [comment]
Looks good!

**Comment by pwalsh** [comment]
@gvidon reopened. the scroll of the comment box is weird for me, and it also causes horizontal scroll bars on a standard laptop.

1. I added arrows and a line to the UI mock to emphasis where the comment action should should to
2. Just use the word "Comment" and put it in a button `class="btn btn-primary"`, and ensure the word comment is in a gettext function

**Comment by pwalsh** [comment]
done.
