### ISSUE TITLE
Allow a reviewer to ask a submitter a question

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#582]
# User story

AS A reviewer I want to email the submitter of the data SO I can ask them question and have a reliable review.

# Implementation

We'll use [Mandrill](https://www.mandrill.com/) as a transactional email backend. 

Users should never see another user's email, so messages will be send from the system to the recipient, but the recipient has to come back to a page on the app in order to respond. 

All messages are therefore persisted in the database so that they can be displayed on the submission page, along with the form for submission.

Messages are only visible to the submitter and reviewer. They are not visible to any other user.

# Mocks

## Communication page

<img src="https://docs.google.com/drawings/d/1FFtJe5xyIw8zN4slkNGeyAt3OkXDXd23opIUVynL5vI/pub?w=960&amp;h=720">

## Integration on the Submission page

<img src="https://docs.google.com/drawings/d/1NnFRD8M7u3LSaNII0hNBVjuXIUg70YvIRZ3Sb3TkweY/pub?w=960&amp;h=720">

# Tasks

* [ ] Configure a Mandrill account
* [ ] Setup config vars and associated env vars for the Mandrill credentials
* [ ] Add a new "communication page" (see mock)
  * [ ] route: `submission/:id/communication` 
  * [ ] Accessible only to authed users
  * [ ] Accessible only to reviewers, if no existing messages exist
  * [ ] Accessible only to reviewers and the submitter, if messages exist
* [ ] On the submission page (`review.html`), in the section where there are notes for the reviewer, and a place for the reviewer to comment + publish or reject the submission, add another link:
  * [ ] "Ask the submitter a question"
  * [ ] Visible only to reviewers 
  * [ ] Links to communication page
  * [ ] If the submitter is anonymous, then the above link cannot be displayed, because it is impossible to email the submitter.
* [ ] Have a new handler for the communication page for messages. POST to the same page, and respond back with appropriate flashed messages ("You message has been sent to X" or "Something when wrong when we tried to send your message {ERROR_MSG}")
* [ ] Have a new model "EntryEnquiry" with the following fields
  * id (uuid)
  * message
  * submitter (FK to submitting user)
  * reviewer (FK to reviewing user)
  * The default timestamp fields, as per the rest of the app
* [ ] Sending a message does the following
  * [ ] Save the message in DB
  * [ ] Send the message as email via Mandrill, the message will have a link back to the communication page

**Comment by Stephen-Gates** [comment]
I like this idea.

**Comment by pwalsh** [comment]
@morchickit see the mocks, note the planned implementation, and add any comments here :).

**Comment by morchickit** [comment]
Looks good!
Why do we have reject and approve? Can you explain about that please?

**Comment by pwalsh** [comment]
@morchickit there are two mocks above:

"Communication page" is a separate page that shows the communication, has the ability to add  comment, etc.

"Integration with submission page" is the current submission page, where next to the **existing** publish and reject buttons, we add a new button to "ask the submitter a question"

**Comment by pwalsh** [comment]
The implementation will really on comments, the changes in #608 and #581
