### ISSUE TITLE
Notify submitters of comments made on a submission

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#608]
# User story

As a submitter I want to know if there is a comment on my submission so that I can respond.

# Implementation

Comments are made via Disqus, as implemented in https://github.com/okfn/opendatacensus/issues/581.

Emails will go through Mandrill, which is a transactional email service provider.

At regular intervals, (example: every 6 hours) we will run a task that checks the comments made on disqus in the interval since the last task was run, and for each comment, resolve it to the submission it belongs to. This gives us an array of submissions that have new comments, which should then be uniqified, as there could be multiple comments on a single submission.

For each submission in this array, we get the submitter. If the submitter is anonymous (`user.providers === {"okfn": "anonymous"}`), we disregard that submitter. Otherwise, we send an email to that submitter that basically says: "Your submission to the {{ sitename }} Census has been commented on. Go to {{ submissionurl }} to read the comments."

# Tasks
 
* [x] Use a package for sending email from Node. I found this https://github.com/eleith/emailjs but check if there is something better (I haven't used this) ?
* [x] Add a transactional email backend (Mandrill). Setup as normal config/env vars for anyone to hook into via env vars, as per most other settings
  * [x] SMTP_HOST (default 'smtp.mandrillapp.com')
  * [x] SMTP_PORT (default 587)
  * [x] SMTP_USERNAME (default 'noreply@census.okfn.org')
  * [x] SMTP_PASSWORD (default '')
    * Note that the password is the Mandrill API key. Has been sent to @gvidon 
* [x] Add a new model: `NotificationLog`
  *  [x] Fields: `id` - uuid or auto-increment; `type` string, signifies the type of notification; `last` datetime, means the datetime of the last processed object for this notification type
  * For our issue here, type is `comments`
* [x] Use a lib that integrates with the disqus API (this looks decent: https://github.com/jmdobry/disqus-node)
* [x] Setup config settings for disqus API access 
  * [x] DISQUS_API_KEY
  * [x] DISQUS_API_SECRET
* [x] Write a function that gets all comments since last processed (latest timestamp in `NotificationLog` for type `comments`) for our disqus forum
  * note that there is a special query format available on disqus. For example, it is possible to get comments via the URL they appear on with something like `thread=link:{LINK}`. Seeing as we need to resolve comments to a submission, this might mean you have to query in a particular way, as, by default, the `listPosts` endpoint does not contain info on the URL the comment originates from
  * There are similar examples on the README for `disqus-node`
* [x] Write a set of functions that:
  * Note that we may have other notifications in the system later, so we want to consider this in design (within reason). The flow is something like `[1. EVENT TO TRIGGER NOTIFICATION] > [2. COLLECT NOTIFICATIONS] > [3. BUILD EACH NOTIFICATION] > [4. SEND NOTIFICATION]`.
  * [x] resolves submissions/submitters from the comments
  * [x] Prepares an email for each submitter
  * [x] Simple HTML template for the email
    * eg: pass a context and a template, and create an email object which has html body, subject, to, from, etc.
  * [x] Sends email
  * [x] Adds new object to the notification log for this type, with timestamp of the last object processed 
* [x] <del>Put these emails on a queue and process from queue ( looks good: https://github.com/Automattic/kue and here is an example setup with Express https://gist.github.com/mojodna/1251812)</del> Let's skip the queue for now.
* [x] Wrap the functionality into a function task that can be called periodically
* [x] Add a cron file that calls this task
  * We'll call using the Heroku scheduler, not cron, but, the cron file may be useful in local development and adding it is quite easy
* [x] Unit tests for all functions

Note that the tasks above are mostly described for the current user story in this issue. However, we will have other "notification types", so consider this when design code (modularity, etc.)

**Comment by gvidon** [comment]
@pwalsh will submitter always has Disqus account?

**Comment by gvidon** [comment]
@pwalsh how will be NOTIFICATION_TASK_FREQUENCY applied? Will we have to copy it from local app config into cron/heroku scheduler config?

**Comment by pwalsh** [comment]
1. Submitter may or may not have disqus account - we do not get the submitter from disqus though. We get the comment, and from that we get the submission that comment belonged to, and then from that, we get the submitter.
2. Yes, we'll be responsible for *manually* ensuring that the schedule (outside the app, be it cron or Heroku or whatever) matches that of the var we set.

**Comment by gvidon** [comment]
So, we will also need some function that sync local app config and scheduler?

**Comment by gvidon** [comment]
As for queues, if you ask me I would say that perhaps there will not be as much load in 6 hours interval as required for queueing the process. I would rather go with some async/workers within the process that queries disqus and sends emails.

**Comment by pwalsh** [comment]
@gvidon 

1. "sync local app config and scheduler" - Not quite sure what you mean. I don' think there is a need to sync anything... but am I missing something?
2. queues - sounds fine with for me - less overhead, and almost definitely we can manage the load.

**Comment by gvidon** [comment]
@pwalsh I mean set up NOTIFICATION_TASK_FREQUENCY from app config in scheduler config. Probably I missed something.

Perhaps in 6 hours interval we will be able to perfectly manage load within single process, not introducing other tools. But again — I may be wrong and not deep enough in architecture design.

**Comment by pwalsh** [comment]
@gvidon I updated the original issue based on our discussion yesterday.

**Comment by pwalsh** [comment]
@gvidon we'll also skip the queue on this implementation. Let's get it working, and then we'll add a queue later if we definitely need it. I updated the tasks to reflect this.

**Comment by gvidon** [comment]
@pwalsh I have pushed incomplete code for both comments checker and email notifications scripts, it is not tested well.

**What is left**
In comments checker
- [ ] unit tests
- [ ] update ```NotificationLog```
- [ ] template import

In email notifications
- [ ] unit tests
- [ ] template rendering

**Comment by vlevit** [comment]
Hi,

It seems we can avoid iterating over N entries and making N `posts.lists` api calls to know which submissions the comments belong to. We can ask the api to include thread for every comment as follows

    disqus.posts.list({
      forum: config.get('disqus_shortname'),
      related: "thread",
    })

and get submission from `thread.link`.

Another point is to use `since` parameter to fetch only new comments. After playing a bit with API through Disqus console, I came to conclusion that the parameter doesn't always mean "since". It works as follows:

    since = date, order == desc  ---> retrieve all the posts before the date
    since = date, order == asc  ---> retrieve all the posts after the date

So we have to set `order` to `asc`. So the disqus query will look like

      disqus.posts.list({
        forum: config.get('disqus_shortname'),
        related: "thread",
        since: N.lastAt.toISOString()
        order: "asc"
      })

**Comment by pwalsh** [comment]
@vlevit looks good.

**Comment by vlevit** [comment]
So currently we have a script `check-comments.js` which can be run from cron for sending notifications and `email.js` which provides email-related utility functions. We send emails in both formats text and html. As it is considered a good practice always to have a plain-text fallback. We use a markdown file under `scripts/templates` as a template for nunjucks so we get both plain text (markdown) and html from a single file. If need a reach html in the future we can separate files for different formats.

I'm still not sure about how to organize the code. Should we `email.js` move somewhere outside from `scripts/`? Should `templates` reside in `census/views/email/`?

> Adds new object to the notification log for this type, with timestamp of the last object processed 

The fact that we do not store notification data/content in NotificationLog and Artem's query with no order specification made me think that we store only the latest log entry per type. Am I wrong? If I'm not then we probably update the log entry instead of adding a new one. Also currently we store the latest date when the script was run, not the timestamp of the latest comment processed. If we stored the comment timestamp we would get the latest comment Disqus many times (ok, we can adjust timestamp - but how much we should add not to skip any other comment?). Also this way `lastAt` is a good indicator if `check-comments.js` was run recently or not.

Currently we're connecting to smtp server each time we're sending a single email, though we can probably connect once per run and send all the emails within a single connection.

**Comment by pwalsh** [comment]
@vlevit please change the behaviour with `NotificationLog` so that it actually creates and queries a log - not just a single object per "type" that gets updated.

Also, what is the status? Is the issue done, and tests are complete? Has it been deployed to the staging server?

**Comment by vlevit** [comment]
@pwalsh This branch is not merged and is not deployed anywhere since it's had open questions and the tests don't cover all the functions. I switched to more high-priority tasks.

As regards to tests. To reach 100% coverage of check-comments I believe we need to run a local smtp server and simulate responses from disqus. Probably for running smtp server we can try approach used in [emailjs tests]. As for disqus probably we'll need to run a server and trick the library to send requests to the local server. Though I don't know if it's possible.

[emailjs tests]: https://github.com/eleith/emailjs/blob/master/test/message.js

**Comment by pwalsh** [comment]
@vlevit ok. just note my comment above:

> please change the behaviour with NotificationLog so that it actually creates and queries a log - not just a single object per "type" that gets updated.

**Comment by pwalsh** [comment]
@vlevit note, I've now added a staging Disqus account: 'opendatacensusnext'. Our staging server is already configured to use it.

Please put finishing this task as high priority on Monday.

**Comment by pwalsh** [comment]
DONE.
