### ISSUE TITLE
Add discussion forum to main navigation

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#609]
# User story

As a Submitter or Reviewer I want to know where I can “escalate” policy or systematic issues to so that they can be resolved

# Implementation
 We need a new config setting called "discussion_forum", with a default value of an empty string. We'd expect the value of this, if filled in, to be a URL, but we don't need to validate that. For the main navigation of the site, we'll append a new navigation link "Discussion", IF we have a value for discussion_forum.

# Tasks

* [x] Create a new config setting called "discussion_forum", with a default value of `''`. Like many other settings, allow this to be set from env vars: `DISCUSSION_FORUM`
* [x] Add the appropriate HTML and logic to the [base template](https://github.com/okfn/opendatacensus/blob/develop/census/views/base.html) to display this link when we have it
  * [x] Note the use of gettext() in the template layer, and use it for this link too

**Comment by pwalsh** [comment]
Done.
