### ISSUE TITLE
Validate submission answers

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#610]
# User story

As a Submitter I want to have my submission checked for basic validity so that I do not accidentally make inconsistent statements (e.g. that the data is open but there is no link to the open license etc).

# Implementation
 
We currently do implement a server-side validation when data is submitted, but is is just at a field level - ensuring certain fields meet certain conditions.

* We use [express-validator](https://github.com/ctavan/express-validator)
* We have some config for it [here](https://github.com/okfn/opendatacensus/blob/develop/census/app.js#L40) (note we already have some custom validator definitions)
* We [validate the request body here](https://github.com/okfn/opendatacensus/blob/develop/census/controllers/census.js#L127)
* And this is the definition of the function that we call, [here](https://github.com/okfn/opendatacensus/blob/develop/census/routes/utils.js#L67)

The new implementation will be to add conditional logic in this validation process, based on a textual description of dependencies between questions, and thereby check/raise new errors when needed.

Note also the [default question sheet](https://docs.google.com/spreadsheets/d/1nwmk8uJEK-4K6-5SdBgoLUlUos-BhfYRgjS74YkhDGc/edit#gid=3). These are loaded in the database but the spreadsheet gives you a nice overview. Note two fields: "id" and "dependants". "id" is the unique identifier for a question (it is actually unique in the scope of a single "site" in the DB), and the "dependants" field is a list of questions that **depend on** the given question. If you look at the submission form ([EG](http://global.census.okfn.org/census/submit/)), you'll see that dependant questions are nested under their parents.

# Tasks

* [x] Update to latest version of `express-validator`, and check for any API changes
  * if there are API changes, first, refactor the current function "as is" for the new API
* [x] Change the name `validateSubmitForm` to `validateData`
* [x] This should really be in `controllers.utils`, so you can move it there, and update the imports for it accordingly (see logic below)
* [x] Implement the new logic for validating data based on the updated description of dependencies
* [x] Add a number of units tests that check some dependancy scenarios
 
Logic from the [survey flow diagram](https://docs.google.com/drawings/d/1jj0mnDjvzz-O8SNBgEhNTqsXa8SNdMoMeoxPoy-tBfE/edit)

**Comment by pwalsh** [comment]
DONE.
