### ISSUE TITLE
General UI/UX  bugs

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#618]
* [x] On submission/review page, remove UUID from the title
* [x] On submit form and submission/review page, content can overrun boxes like "Current Entry" when there is a lot of text. See example in #592
* [x] Weirdness with table heading when scrolling
* [x] Some markdown not being rendered. See example in #604 
* [ ] Too easy to accidentally submit when in middle of data entry. See example in #602
* [ ] Data format typeahead not working on Safari (and maybe others?). See #440
* [x] Inconsistent popup formatting. See examples in #507 #566
* [x] Awkward text wrapping on entry pages. See #566

**Comment by pwalsh** [comment]
@morchickit please see the list above, and confirm what we want done now.

**Comment by pwalsh** [comment]
@morchickit I'm unassigning myself from this. Can you let me know if something here is critical?

**Comment by morchickit** [comment]
Didn't we do 604?

**Comment by pwalsh** [comment]
@kravets-levko I'm assigning to you to look at if you get time. note that some tasks are done.

**Comment by borysyuk** [comment]
https://github.com/okfn/opendatacensus/pull/696

**Comment by pwalsh** [comment]
The two tasks left become irrelevant as we are redoing the submission/review form.
