### ISSUE TITLE
Better UI/UX to understand current "state of play"

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#619]
# User stories

As a (Potential Submitter) I want to know which datasets for a country (or just generally) have not been checked this year so that I can go check them and update them if needed or leave them as is if ok.

As a Visitor/Submitter I want to know when an Entry was made / updated so that I can judge how likely it is to still be valid.

As a Submitter I want one clear and marked way to enter data so that I won’t get confused when trying to submit data.

As an Index local Coordinator I want to have reports on the progress of populating the index so I can will know where to put my efforts.

As the Editor I want to have a report of the status of all of the index so that I can see the Coordinators are doing their job and evaluate whether we on track with submissions.

# Implementation

All table displays will be updated with a range of new information, and the display of information and actions a user can take will be dependant on the current state of a given entry/submission.

This means that all views that display tabular views on the data will require a different approach to querying and data processing - in particular, we always need to know the current entry and the current state of submissions, for each entry record, in order to display appropriate information.

For further context on some of the factors that lead to this new feature set, see #601 #599 #595, and  https://www.marqueed.com/collections/176586/images/852696

The most critical aspect of this is the display of entry/submission information in the tables. Here is a high level run down of what we are aiming for:

<table>
  <thead>
    <tr>
      <td>
      </td>
      <td>No Entry
      </td>
      <td>Old Entry
      </td>
      <td>Current Entry
      </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>No Submission
      </td>
      <td>Add button (direct to submit with prefill)
      </td>
      <td>Entry shown but highlight “vintage” or that it is old in some way … [TBC] + (maybe) add button or similar
      </td>
      <td>Normal display (as per old approach)
      </td>
    </tr>
    <tr>
      <td>Submission
      </td>
      <td>Review button
      </td>
      <td>Show entry as per no submission and also that there is a submission to review
      </td>
      <td>Show entry as per normal and that there is a submission to review … 
      </td>
    </tr>
  </tbody>
</table>

# Tasks
 * [x] Refactor the way we query for data so we have a modular pattern to apply to our expanded data needs
  * [x] There will be an abstraction called `getData` that takes an options argument, and has two internal steps: (i) query, (ii) process. Obviously, `query` will perform the SQL queries, similarly to the current `loadModels` util, and then `process` will perform the common processing tasks before we return data for specific treatment/rendering in a given controller. This will return a promise with all data as the result, and simplify a lot of the code in controllers that essentially repeats the same thing. It won't be the same as the old logic as our needs have changed and are changing, but will be based on same data access layer principles rather than directly having ORM calls in the controllers

* [x] Each object in a table needs to hold
  * [x] Its current state (eg: entry or none if no entry)
  * [x] Its pending state (eg: are there valid submissions waiting for review)
* [x] Indicate the age of the object
  * [x] `year` and `updatedAt` (possibly only relevant on place/dataset tables, but i think we can make this somehow on the overview too, so that we don't just rely on color to indicate vintage)
    * [x] On place (and dataset?) page, `year` column > `last updated`. Show year, and on hover show `updatedAt` (+ submitter/reviewer?)
    * [x] If date not this year, follow same color coding logic as described below for the background of overview table cell, but here is the background of the year label
* [x] Indicate pending submission
* [x] Conditions for button text and action: add, review, etc.
* [x] Indicate vintage of a submission with background color
  * [x] no BG color if obj.year is current year
  * [x] orange BG if obj.year is current year -1
  * [x] red BG of obj.year is current.year - 2 or more
* [x] All actions to add information should now satisfactorily go via table data
  * [x] Remove the generic "add information" button
* [x] Fix UX bugs with this page - eg - place sorting. It is related to #575 which I previously did not escalate, as I did not realise that our UI called all the data *again* via api as well as the server rendering.

**Comment by pwalsh** [comment]
@morchickit @rgrp I've extracted a task list for myself out of the user story notes we have. Please have a glance and add any comments if you think I've missed something - we are covering a lot of ground here and I want to ensure we get it close to right on first take :).

**Comment by morchickit** [comment]
Looks good do me!

**Comment by rgrp** [comment]
Generally looks good. One point I've noticed so far:

* Is this just about front page or also about the "place" page (the colouring of "year / last updated" vintage needs to happen there as well)? Personally I would split this out as a separate issue so we don't get confused.

**Comment by pwalsh** [comment]
Definitely I was dumping both in here, yes. I can split them out, agreed.

**Comment by pwalsh** [comment]
DONE.
