### ISSUE TITLE
Get rid of /census/ in urls

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#635]
E.g. /census/submit should be simply /submit/ etc

I discussed this with @pwalsh before he went away and we agreed the `/census/` was unnecessary. Minor but may be nice to fix before we go live especially as may break certain links and we will share urls like the submit link ...

/cc Up to @morchickit to prioritize or not

**Comment by pwalsh** [comment]
This is 1-2 hours work, and should be done before we go live with global census IMHO.

# Tasks

* [ ] grep for `/census/submit/` and `/census/submission/` in templates and controllers, and get rid of `/census`
* [ ] Change the way that the census router works. The code is an Express v4 app, and tries to use the Express routing system that was introduced in v4. The [current `/census/` routes follow this pattern](https://github.com/okfn/opendatacensus/blob/develop/census/routes/census.js). Other routers in the app are "mock" routers, such as the `system` one [here](https://github.com/okfn/opendatacensus/blob/develop/census/routes/system.js#L8), which is actually instantiated in the `pages` router [here](https://github.com/okfn/opendatacensus/blob/develop/census/routes/pages.js#L22), which allows for more flexible url patterns. So, we need to adjust the `census` router to be like this:
  * [ ] Patterned after the `system` router, it takes a router as its only argument, and other related changes in the function body
  * [ ] Instantiated in the `pages` router, so that the routes do not have to be mounted on the `/census/` path
  * [ ] Remove the [direct use of the census router here](https://github.com/okfn/opendatacensus/blob/develop/census/app.js#L111), as it will be mapped via the pages router

That should be it...

**Comment by pwalsh** [comment]
FIXED.
