### ISSUE TITLE
Assets versioning

### ISSUE THREAD

**Issue by vlevit** [okfn/opendatacensus#645]
Every time we change JS or CSS files and deploy to the production we put users that have those files in the browser cache at risk that they get the broken page or not working functionality until they reload the page. It's because by default browsers don't always send requests for resources on every page visit if they have those files in the cache.

The solution for this issue is to use versioning. Every time the asset changes it gets a new URL. I was doing this manually several times. Though it should be automated. There are a plenty of tools for doing this. As we already use gulp we can consider gulp extensions like: gulp-rev-hash, or gulp-rev or any other which would suit our needs.

Another benefit of using assets versioning is an ability to set the far future expires headers for the assets files. This will reduce the number of requests browsers send to the server. You can read more on this technique [here](https://developer.yahoo.com/performance/rules.html#expires).

**Comment by pwalsh** [comment]
@vlevit agree this is important, especially with the amount of changes we have made. Let's do it in this sprint.

**Comment by pwalsh** [comment]
@kravets-levko another one to look at if time permits.

# Tasks

* [ ] We should build/bundle our public (front end) assets (jss and css)
  * [ ] Note that you can use gulp tasks that we already have on other code bases you are working on
* [ ] We should version them as noted above
* [ ] We should have a build task for developers to run locally and build assets, but also, a `postinstall` script so that when we deploy to Heroku the files get build before the app starts serving (again, you have a reference for this in other projects)

**Comment by borysyuk** [comment]
https://github.com/okfn/opendatacensus/pull/708
now our css and js links are like this: <link href="/css/style.css?{{currentTime}}" rel="stylesheet">
currentTime - it is time in unix format when node application has been started. 
currentTime will be different after each application restart.
