### ISSUE TITLE
Add conditions to unsure

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#688]
A simple example: if "exists" is "Unsure", then without conditions, "digital" could be "Yes", which would obviously be wrong.
see here- https://discuss.okfn.org/t/health-datasets-what-do-we-want-to-measure/506/28

**Comment by Stephen-Gates** [comment]
In addition to correcting the survey, can this page also be updated http://census.okfn.org/survey-flow/ ?

**Comment by pwalsh** [comment]
The edge cases that this causes weird behaviour in will be further reduced in https://github.com/okfn/opendatacensus/issues/693 because all fields with data from the previous entry will be visible to the user (and therefore easily changed).

**Comment by pwalsh** [comment]
So @morchickit how should the behaviour be?

I'll give an example:

If "digital" is Unsure, do "online", "machinereadable" and "bulk" all need to be "Unsure"? (If "digital" was "No", they'd all have to be No).

So, the methodological issue here is:

* If a parent is "Unsure", does that mean all children are also "Unsure"? (same pattern as how "no" works)
* If not, what is allowed for children when the parent is "Unsure"? We need to have the general pattern. If there are specific exceptions, we also need to understand in order to code it. Example: could "digital" be "Unsure" but "bulk" be "No"?

**Comment by pwalsh** [comment]
Talked with @morchickit 

* If digital is Unsure, then all its conditioned questions are Unsure
* For others, if they are Unsure, the others have no condition (can be Yes, No, or Unsure)

**Comment by pwalsh** [comment]
# Tasks

The current logic is here: https://github.com/okfn/opendatacensus/blob/develop/census/controllers/utils.js#L15 and the validator, with a description of how it current works is here https://github.com/okfn/opendatacensus/blob/develop/census/controllers/utils.js#L73. The tests are here https://github.com/okfn/opendatacensus/blob/develop/tests/submissions.js

* "Yes" is `true`
* "No" is `false`
* "Unsure" is `null`

* [ ] Ensure that `expectFalse` only applies when the head question is "No", not if it is "Unsure"
* [ ] For the `exists` question, ensure that if it is "Unsure", then all its conditions questions are also "Unsure"
* [ ] For the other questions that have an `expectFalse` array in their validator, ensure that if it is "Unsure", then any of those conditional questions can have any value

**Comment by borysyuk** [comment]
done https://github.com/okfn/opendatacensus/pull/701
