### ISSUE TITLE
Simplify show/hide of fields on form

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#693]
# Description

In the last codebase of the census, we introduced [additional conditions between questions](https://github.com/okfn/opendatacensus/blob/develop/census/controllers/utils.js#L16). These conditionals help us collected more standardised data.

The condition checks are done servers-side.

We also decided to mimic the server-side checks in the client, and additionally, show/hide fields based on these conditions. [That work was talked about here](https://github.com/okfn/opendatacensus/issues/623). This meant that we went from a fairly simply show/hide pattern in the question display of the form, to one where the show hide was more complex.

The new show/hide code uses conditions, [as you can see here](https://github.com/okfn/opendatacensus/blob/develop/census/public/src/submit.js#L3), whereas previously, it was a [simpler affair of showing "dependant" questions if the "parent" had a YES answer](https://github.com/okfn/opendatacensus/blob/2e7816c20f3f7585d7aa6e0d362de4b81767f209/census/public/src/submit.js#L50).

The idea behind the more complex UI was a good one, but, it has caused some issues with edge cases of data. I even recently introduced a [little hack to work around such an issue here](https://github.com/okfn/opendatacensus/commit/333318eb85b9ee2c2cbb98bb7b2475a420b24188).

# Tasks 

We want to simplify again:

* [x] Remove the new code that does show/hide based on conditions
* [x] Revert back to a situation where:
  * [x] If a parent question is "Yes", show the dependants
  * [x] Additionally, because in the new methodology, we've moved some dependants to new parents, if a parent is "No" or "Unsure", but any dependant has a value, then, show that parent's dependants. (This ensures that old data does not cause weird edge cases in new form layouts as methodology changes)
* [x] Remove the [recently introduced hack](https://github.com/okfn/opendatacensus/commit/333318eb85b9ee2c2cbb98bb7b2475a420b24188) mentioned above

**Comment by borysyuk** [comment]
done https://github.com/okfn/opendatacensus/pull/697

**Comment by pwalsh** [comment]
FIXED.
