### ISSUE TITLE
Updates to API

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#704]
Notice that I refactored the new API to use our data access layer via `getData`: https://github.com/okfn/opendatacensus/blob/develop/census/controllers/api.js#L169

There are a bunch of options here: the important one being the cascade option.

When cascade is false, then any query for data for a given year will return only records that exactly match on that year.

example: if I queried for 2015 entries, with cascade false, then I'd only get records that are actually submitted in 2015.

When cascade is true, the same query will also bring forward records from previous years, IF a record in the current year does not exist (based on the tuple of site, place, dataset, year).

So, the cascade option ensure that, even if a particular dataset has had no entry for the year being queried, we will show something for it if an entry was made in a previous year.

# Tasks

* [x] `entries.all` - every single entry in the system for the given site - regardless of state (`isCurrent` can be `true` or `false`, for example - ensure to show all fields)
* [x] per year, `entries` are the actual entries of that year, and `entries.cascade` are the entries for that year, including those brought forward
* [x] Submitter and Reviewer data: there should be fields "submitter" and "reviewer" - these should just be the full name of the submitter/reviewer, or "anonymous" if so.

**Comment by pwalsh** [comment]
FIXED.
