### ISSUE TITLE
Modify data for censuses currently doing sprint that spans a calendar year

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#738]
# Description

Some census instances are doing a data collection that spans end of 2015 -> beginning of 2016. The data collection should belong to 2016, and there was misunderstanding as to the nature of the census cycle as it relates to the calendar year. To assist these census admins on this, we'll collect all pending entries from 2015, and change their year (and creation date, if required) to 2016, so that these entries appear as part of the 2016 data.

Candidate census instances:

* Chile
* Mexico
* Caribbean
* Science Po

# Tasks

* [ ] Write an SQL statement to modify the appropriate records (not reviewed, not current)
  * [ ] Save it and add it to this issue for future reference
* [ ] Verify locally
* [ ] Verify on staging with approval from @morchickit 
* [ ] Apply modification to the production database (talk with @pwalsh about putting it in maintenance mode for a few mins while doing modification)

**Comment by borysyuk** [comment]
SQL:
update entry SET
year = '2016'
where 
	entry.site IN ('cl-city', 'mx-city', 'caribbean', 'sciencepo') and
	entry.year = '2015' AND
	entry.reviewed = FALSE

**Comment by pwalsh** [comment]
DONE.
