### ISSUE TITLE
Requirements/Spec for survey strategies

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#752]
# Description

The current survey is a set of fixed questions with fixes scores. Some questions are scored, others are not. Attached to the question set is a comment box, and further, a comment thread on disqus. The score are calculated by multiplying the score x datasets - there is no normalisation of scores, and this became evident last year when new datasets were added.

Several people and organisations are using the census code. We've had repeated requests to customise questions, and have never supported this.

Now, given that the methodology for the census is changing, it is an appropriate time to reconsider how we implement questions and scoring in general. We'd like to replace the current hardcoded system with a more dynamic "survey strategy" implementation. 

For a given instance, a {Site Admin} should be able to provide a set of her own questions (without reasonable constraints), the relationship between the questions, the score weighting of the questions.

In combination with the available [_published_ datasets](https://github.com/okfn/opendatacensus/issues/754) for each given year, we can implement an algorithm that takes the given question scores and the dataset count, and always givens a score out of 100 per dataset, and for the whole survey for that year.
## User stories
- https://trello.com/c/eUYx2X6G
- https://trello.com/c/mQ6y2g0L

... and some that are not directly related to the strategy itself, but might inform the implementation nevertheless...
- https://trello.com/c/9rYP4lou
- https://trello.com/c/NbVToewe
- https://trello.com/c/zKBubLpS
- https://trello.com/c/vDu9unYr
- https://trello.com/c/dxA532yT
# Tasks
- [ ] Write a spec or requirements doc for implementation
- [ ] Create some notes on possible issues with old data and structure
- [ ] Estimate of time

**Comment by brew** [comment]
# Datasets, QuestionSets, and Questions

## Some statements

- `Questions` are collected together in `QuestionSets`.

- `Datasets` have an associated `QuestionSet`.

- `QuestionSets` have a `QuestionSetSchema` object (json) to map positions, relationships, and dependent states between `Questions`.

- A `User` creates an `Entry` to answer `Questions` about a `Dataset`.

- As an `Entry` is completed, an `answers` object (json) is populated.

- A `QuestionSet` instance can validate an `answers` object, returning a `QuestionSetState` object (json).
    - Validates against the `QuestionSetSchema`
    - and validates against `Question`-specific validation

- A `QuestionSetState` object can be used by the UI to setup the current state of the entry form.

## `QuestionSetSchema`

A `QuestionSetSchema` provides the structure and dependency graph for a set of `Questions`.

This attempts to decouple `Question` objects from information about the relationships and hierarchy between `Questions`, leaving `Questions` to be as stand-alone as possible.

Here is a `QuestionSetSchema` for this example set of questions:

1. Do you like apples?
    - 1.2. Do you like bananas instead? (shown when 1 is 'No')
2. Do you like RED apples? (enabled if 1 is 'Yes')   
3. Have you eaten a red apple today? (enabled if 2 is 'Yes')
    - 3.1. Did it keep the doctor away? (shown when 3 is 'Yes')

```javascript

[
    {
        // The question is "Do you like apples?"
        "id": "like_apples",
        "position": "1",
        "defaultProperties": {
            "visible": true,
            "enabled": true,
            "required": true
        }
    },
    {
        // The question is "Do you like bananas instead?"
        "id": "bananas_instead",
        "position": "1.1",
        "defaultProperties": {
            "visible": false,
            "enabled": false,
            "required": false
        },
        "if": [
            {
                "dependentId": "like_apples",
                "value": false,
                "properties": {
                    "visible": true,
                    "enabled": true,
                    "required": true
                }
            }
        ]
    },
    {
        // The question is "Do you like RED apples?"
        "id": "apple_colour",
        "position": "2",
        "defaultProperties": {
            "visible": true,
            "enabled": false,
            "required": false
        },
        "if": [
            {
                "dependentId": "like_apples",
                "value": true,
                "properties": {
                    "enabled": true,
                    "required": true
                } 
            }
        ] 
    },    
    {
        // The question is "Have you eaten a red apple today?"
        "id": "red_apple_today",
        "position": "3",
        "defaultProperties": {
            "visible": true,
            "enabled": false,
            "required": false
        },
        "if": [
            {
                "dependentId": "apple_colour",
                "value": true,
                "properties": {
                    "enabled": true,
                    "required": true
                }
            }
        ]
    },
    {
        // The question is "Did it keep the doctor away? (optional)"
        "id": "doctor_away",
        "position": "3.1",
        "defaultProperties": {
            "visible": false,
            "enabled": false,
            "required": false
        },
        "if": [
            {
                "dependentId": "red_apple_today",
                "value": true,
                "properties": {
                    "visible": true,
                    "enabled": true
                }
            }
        ]
    }

]
```

## QuestionSetState

Simpler than the `QuestionSetSchema`, providing only the current state of the questions. For example, the initial state of the question set would look like this:

```javascript
[
    {
        "id": "like_apples",
        "position": "1",
        "properties": {
            "visible": true,
            "enabled": true,
            "required": true
        }
    },
    {
        "id": "bananas_instead",
        "position": "1.1",
        "properties": {
            "visible": false,
            "enabled": false,
            "required": false
        }
    },
    {
        "id": "apple_colour",
        "position": "2",
        "properties": {
            "visible": true,
            "enabled": false,
            "required": false
        }
    },    
    {
        "id": "red_apple_today",
        "position": "3",
        "properties": {
            "visible": true,
            "enabled": false,
            "required": false
        }
    },
    {
        "id": "doctor_away",
        "position": "3.1",
        "properties": {
            "visible": false,
            "enabled": false,
            "required": false
        }
    }
]
```

**Comment by pwalsh** [comment]
@brew at a glance, looks great. We def. want to use [JSON Schema](http://json-schema.org) IMHO. JSON Schema v4 (current) does not have `if`, but the v5 proposal has `switch`: https://github.com/json-schema/json-schema/wiki/switch-(v5-proposal)

**Comment by brew** [comment]
Happy for me to close this @pwalsh ?
