### ISSUE TITLE
Implement a survey strategy using the new methodology

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#753]
(Description and Tasks edited by @brew 2016-08-17)
# Description

The broad scope of this ticket is to implement changes to the census entry process (survey), enabling questions, and dependencies between questions, to be displayed dynamically from data inputed by site admins into the current CMS (Google Spreadsheets).

The biggest conceptual change is that `Questions` will be associated with `Datasets`, through a `QuestionSet`. This contrasts with the current implementation where `Questions` are associated at the `Site` level and shared by all `Datasets` in the `Site`.

`QuestionSets` being associated with `Datasets` allows different `Questions` to be used by `Datasets` within the same `Site` (although this will likely not be necessary for the Global index, which will share the same QuestionSet across all Datasets in the Site).

Each `QuestionSet` will have a `QuestionSetSchema` property (json), which will define the relationship between each `Question` (see https://github.com/okfn/opendatacensus/issues/752#issuecomment-238185317 for more details). The `QuestionSetSchema` will be used by the front-end to layout the entry form and determine which fields are required, and need to be displayed and enable, as the entry is completed by the user.
# Tasks
- [x] Implement Question/QuestionSetSchema in (#776):
  - [x] Front-end (Reactjs) for simplest Question types (Yes/No)
  - [x] Structure Front-end code and bundle with webpack
  - [x] Question position (and label?) determined by QuestionSetSchema
  - [x] Simple backend controller with static Question/QuestionSetSchema data
  - [x] Front-end tests
- [x] Question/QuestionSet data imported to db from CMS (#777)
  - [x] Process data to db for changed `Site > Dataset > QuestionSet > Questions` structure
  - [x] Backend controller to use dynamic Question/QuestionSetSchema data
  - [x] Add QSSchema json schema to docs
- [x] Implement front-end design for entry form (#779)
  - [x] Disabled styling
  - [x] Sub-questions
  - [x] Comment placeholder text from data
  - [x] Instructions text from data
  - [x] Instructions reveal javascript
  - [x] `is_godi` site setting used by GODI only
- [x] Implement all Question types
  - [x] Text (#783)
  - [x] Yes/No (#779)
  - [x] Likert scale (#787)
  - [x] Multi-value (custom type for dataset URL) (#794)
  - [x] Multi-choice [see note 1] below
    - [x] Multi-select (characteristics) (#795)
    - [x] Multi-select with Other (file format) (#797)
- [x] A `context` object accessible from the `QuestionSet`. e.g. The context object could be the associated `Dataset`, allowing access to dataset-specific properties within Questions, such as time intervals. (#795, #796)
- [x] Add 'time interval' column to datasets. Used to populate the question "Data should be updated every <TIME INTERVAL>: Is the data up-to-date?" (#796)
- [ ] Ensure new format Questions will work with translation framework (see #788)

There are a large number of tasks here, which may need to be broken up into separate issues/PRs. This ticket will be edited to include issue numbers where appropriate.

[1] The Format question is a scored question that needs to be evaluated against a known list of scorable formats. This may be deferred to the scoring work.

**Comment by brew** [comment]
This is now complete (except for the translations work which now has its own issue). Happy for me to close this @pwalsh?
