### ISSUE TITLE
Allow datasets to be published/unpublished, per year

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#754]
# Description

Last year, we experimented with adding new datasets to the census. We collected data, and then, we decided that these dataset submissions were not of high enough quality, and it was decided to not show them as part of the Index.

This created a whole range of problems, being a use case that the code was never designed for. These problems include incorrect metrics on the census site, incorrect data showing (because we have no mechanism to "remove" a dataset), incorrect metrics via the API, and a whole bunch of custom processing in the Index code to fix these issues and display correct data there.

Having established, the hard way, that we want flexibility to add and remove datasets for a given survey period, we need to write code to support this use case. This starts with a flag to publish/unpublish a dataset *per survey period* (ie: per year), and the use of this flag across the UI, the API, and the scoring/calculation functions.

## User stories

- https://trello.com/c/s1hFxQOQ

# Tasks

-  [x] Add a data structure to the CMS that allows publishing/unpublishing a dataset per year (default is published)
- [x] Make changes to loaders and models to accept this new flag
- [x] Use this flag in the various tables, and also for routes
- [ ] This flag has a significant impact on scoring, but seeing as it will be integrating with the scoring mechanism in https://github.com/okfn/opendatacensus/issues/752 https://github.com/okfn/opendatacensus/issues/753 I'd say ignore that for now
- [x] Tests

@roll seeing as you dealt with this last year, if you have any thoughts, they are most welcome.
