### ISSUE TITLE
Allow datasets to have a list of characteristics

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#755]
# Description

In order to help improve the quality of submissions for datasets, we want a list of dataset characteristics to help the submitter and reviewer ensure "apples are apples". Some work was [done in this direction last year](https://github.com/okfn/opendatacensus/search?q=characteristics&type=Code&utf8=✓), and then removed.

## User stories

- https://trello.com/c/zAORqsKL

# Tasks

- [x] Add a data structure to the "CMS" for listing characteristics for a dataset (was partially implemented last year)
- [x] make relevant model/loader changes
- [x] Expose the list of characteristics on the dataset pages, and also on submission/review forms (just for reference, as this depends on redesign)
- [ ] Tests for loading/handling dataset characteristics

**Comment by brew** [comment]
@pwalsh: Instead of a number of `Characteristics:n` columns, how about a single column that can take a markdown snippet? We would suggest the admin should populate with a short markdown list. It would be simple, and flexible. Any downsides to that, over multiple columns?

**Comment by pwalsh** [comment]
@brew yes: we need it structured, to generate text boxes and so forth. essentially, we need it to get in the database as an array.
