### ISSUE TITLE
UI/X for survey questions based on new methodology

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#756]
# Description

The UX of the form for submitting and reviewing the data has been a sore point in the last few years. Given the [new methodology](https://discuss.okfn.org/t/introducing-the-new-proposed-global-open-data-index-survey/3104), and the [new approach](https://github.com/okfn/opendatacensus/issues/752) we'll take to implementing questions, we are simply rebuilding the survey form from ground up.

# Tasks

- [x] Mockups (html) for a new survey form
- [ ] Sign off from @KateRogers as product owner
- [ ] Sign off from @brew as tech lead and implementor

**Comment by smth** [comment]
http://okfnlabs.org/census-mockup/form/
