### ISSUE TITLE
Consolidating design across Index and Census

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#757]
# Description

*This is a meta issue which will be broken down into distinct issues based on decisions between @smth @brew and @pwalsh*

We want to bring the [Census](http://global.census.okfn.org) and [Index](http://index.okfn.org) designs closer together. In fact, we want to generate the Index from the Census codebase ([ref.](https://trello.com/c/PM7LjKm6), [ref.](https://trello.com/c/3tQEO31y)) so we keep the benefits of distinct web properties, but reduce the overhead of maintaining two sets of logic and ui.

The Index UI is written with bootstrap 3, and is generally more modern in various ways than the current Census UI. I suggest we: 

- Start from the Index UI
- Work out what high-level branding changes we want to make this year
- Work out which elements are common, and which elements are specific to Index or Census
- Do a series of page by page mocks

## User stories

- https://trello.com/c/uboCfkD3

### Home

- http://global.census.okfn.org
- http://index.okfn.org

### Dataset overview

- http://global.census.okfn.org/dataset/statistics
- http://index.okfn.org/dataset/

### Place overview

- http://global.census.okfn.org/place/tw
- http://index.okfn.org/place/

### Entry

- http://global.census.okfn.org/entry/tw/timetables
- http://index.okfn.org/place/united-kingdom/companies/

Note that we want to add new, interesting info to the entry pages too:

- https://trello.com/c/6H4KXEU5
- https://trello.com/c/tZMTTazz

### Generic

- http://global.census.okfn.org/about/
- http://index.okfn.org/methodology/

# Tasks

- [ ] Discussion on approaches from a design perspective
- [ ] Discussion on approaches from an implementation perspective
- [ ] Break down into a set of discrete issues for ui/x work

**Comment by smth** [comment]
Some notes on approach, and work so far:
- Used the new [survey form](http://okfnlabs.org/census-mockup/form/) as a starting point:
https://github.com/okfn/census-mockup

- Added CSS and JS from the Index code (file structure slightly different, not fully tested)
- Created a static version of a dataset page from the Index
- Started adding elements from the Census dataset page
- Index/Census specific elements are included depending upon what [mode](https://github.com/okfn/census-mockup/blob/master/templates/layout.html#L1) the site is in

Resulting new dataset page (WIP): http://okfnlabs.org/census-mockup/dataset/

**Comment by smth** [comment]
## Pages

### Home
- http://okfnlabs.org/index-mockup/
- http://okfnlabs.org/census-mockup/

### Dataset overview
- http://okfnlabs.org/index-mockup/dataset/
- http://okfnlabs.org/census-mockup/dataset/

### Place overview
- See dataset overview

### Entry
- http://okfnlabs.org/index-mockup/entry/
- http://okfnlabs.org/census-mockup/entry/

### Generic
- http://okfnlabs.org/index-mockup/generic/
- http://okfnlabs.org/census-mockup/generic/

**Comment by pwalsh** [comment]
this was DONE. specific tasks are covered in specific.
