### ISSUE TITLE
Entry form submission and review for new methodology

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#784]
Using the form created as a result of #753, create a new `Entry` instance from the data submitted. Entries can be reviewed by an authorised reviewer.

Submission:
- [ ] Validation (moved to #829)
- [x] Pre-populate form fields with answers, if available (#814)
  - [x] Yes/No
  - [x] Text
  - [x] Likert
  - [x] Multichoice
  - [x] Source
  - [x] Comment box
  - [x] About You
  - [x] Anonymous
  - [x] Other Comments
- [x] Create entry from successfully submitted and validated data (#815)
- [x] Current Entry values represented on form (#824)

Pending:
- [x] Entry review state (pending, reviewed, accepted) (#820)

Review:
- [x] Review design for Review process (with input from @smth) 
- [x] Show current values (if existing) (#824)
- [x] Reviewers can change review state of entry (#820)
  - [x] Accept
  - [x] Reject
- [x] Accepted entries are promoted to 'current' (#820)

**Comment by brew** [comment]
This is now complete. Entry form validation has been moved to #829.
