### ISSUE TITLE
Entry form validation

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#829]
Currently, the entry form doesn't have any validation for data types or required fields. This allows users to submit empty or partially complete submissions, potentially blocking the review queue.

- [x] Basic entry form validation for `required` fields (#837)
- [x] Add validationRule loading from spreadsheet (#838, #839)
- [ ] Remove old validation code (#836)
