### ISSUE TITLE
Localization for Survey

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#844]
During implementation of the new template design and survey strategy for the 2016 survey, localization wasn't explicitly supported. Much of the supporting code is in place, but new strings need to be marked for translation, and Transifex updated.

The strategy for localizing loaded content (Questions, Datasets, etc) has changed. Site admins are encouraged to manage Questions and Datasets within tabs within a single Google Spreadsheet doc (rather than extending a global Questions doc with translated columns).

For local sites where more than one language is supported, the multi-column translation strategy can still be used.

- [x] Prepare strings for general site-wide translations (#858)
    - [x] Mark all template strings for translation
    - [x] Mark all strings in code for translation
- [ ] Strings in jsx files (see #864)
- [x] Ensure loaded content can be localized, loaded, and used in browser
    - [x] Questions (see #788)
    - [x] Datasets (#860)
        - [x] Dataset characteristics (see #859)
    - [x] Multi-language switcher is available where appropriate
- [x] Update localization instructions in documentation (http://census.okfn.org/en/latest/site-admins/#localization) (#863)
- [x] Update README instructions for compiling translations (#863)
- [x] Upload new pot file to Transifex
